- README.md
1. Follow the instructions and make sure they make sense
1. Note that product reviews won't show up unless the SKU matches. You can hardcode a SKU using the instructions [here](https://github.com/takeshape/penny/pull/106)
> Trustpilot README

- .takeshape/pattern/schema.json
- README.md
Additional changes:
- adjusted the heading structure to fix some inconsistencies
- removed the Zendesk endpoint from the pattern
1. Read the README
2. Verify that the headings make sense
> Add Zendesk instructions

- .takeshape/pattern/roles.json
- .takeshape/pattern/schema.json
- src/components/Payments/utils.ts
- src/features/AccountNavigation/AccountNavigation.tsx
- src/features/AccountSubscriptions/AccountSubscriptions.stories.tsx
- src/features/AccountSubscriptions/components/Actions/PaymentMethodForm.tsx
- src/features/AccountSubscriptions/components/Actions/PaymentMethodRechargeForm.tsx
- src/features/AccountSubscriptions/components/ManageSubscription/ManageSubscription.stories.tsx
- src/features/AccountSubscriptions/components/ManageSubscription/ManageSubscription.tsx
- src/features/AccountSubscriptions/components/SubscriptionOverview/SubscriptionOverview.stories.tsx
- src/features/AccountSubscriptions/components/SubscriptionOverview/SubscriptionOverview.tsx
- src/features/AccountSubscriptions/fixtures.ts
- src/features/AccountSubscriptions/queries.fixtures.ts
- src/features/AccountSubscriptions/queries.ts
- src/features/AccountSubscriptions/transforms.ts
- src/features/AccountSubscriptions/types.ts
- src/types/paymentMethod.ts
1. Review the storybook. Test out the `Update payment method` actions on the overview and management screens.
* Because we're using fixtures, testing on the actual site won't really work right now. A more thorough test can be done after Rob's PR merges.
> Integrate Recharge payment methods

- .takeshape/pattern/schema.json
- src/config/auth.ts
- src/features/AccountSubscriptions/AccountSubscription.tsx
- src/features/AccountSubscriptions/AccountSubscriptions.stories.tsx
- src/features/AccountSubscriptions/AccountSubscriptions.tsx
- src/features/AccountSubscriptions/components/Actions/ProductOptionsForm.tsx
- src/features/AccountSubscriptions/components/ActiveSubscription.tsx
- src/features/AccountSubscriptions/components/EndedSubscription.tsx
- src/features/AccountSubscriptions/components/ManageSubscription/ManageSubscription.stories.tsx
- src/features/AccountSubscriptions/components/ManageSubscription/ManageSubscription.tsx
- src/features/AccountSubscriptions/components/SubscriptionOrders/SubscriptionOrders.stories.tsx
- src/features/AccountSubscriptions/components/SubscriptionOrders/SubscriptionOrders.tsx
- src/features/AccountSubscriptions/components/SubscriptionOverview/SubscriptionOverview.stories.tsx
- src/features/AccountSubscriptions/components/SubscriptionOverview/SubscriptionOverview.tsx
- src/features/AccountSubscriptions/queries.fixtures.ts
- src/features/AccountSubscriptions/queries.ts
- src/features/AccountSubscriptions/transforms.ts
- src/features/AccountSubscriptions/types.ts
- src/features/AccountSubscriptions/utils.ts
- src/pages/_app.tsx
- src/pages/account/subscriptions/[subscription].tsx
- src/pages/account/subscriptions/index.tsx
- src/utils/takeshape.ts
1. Go to preview site. Sign in. View your subscriptions.
1. You should only see a single loading skeleton until your subs load.
1. Focus another tab.
2. Go back to your subs, they should not reload.
> Improve subscription fetch behavior

- .github/workflows/lighthouse.yml
- .lighthouse/testPaths.json
- README.md
- src/config/index.ts
- src/config/lighthouse.ts
- src/features/ProductPage/transforms.ts
- src/pages/collection/[[...collection]].tsx
- src/pages/product/[[...product]].tsx
> Update lighthouse URL loading behavior

- .gitignore
- .takeshape/pattern/schema.json
- codegen.takeshape.config.js
- package-lock.json
- package.json
- scripts/prebuild.sh
- src/config/takeshape.ts
- takeshape-project.graphql
1. Make a branch of this branch
2. Locally make a change to the schema and accompanying code. For example you could rename `addMembers` -- then you'd be able to verify if the renamed mutation is used by using the newsletter subscribe form and checking the mutation name in the browser dev tools.
3. Push up your branch
4. Make sure the deploy succeeds at https://vercel.com/takeshape/penny/deployments
5. At the end of the deployment grab the URL from the assigning domains step
6. Make sure your change is reflected in your preview env
7. Make sure your change is not reflected at https://penny-demo.takeshape.io/
8. Review the `schema.json` carefully. I moved over the production schema to the repo and I added a few comments about some details.
> Use branches in Vercel build

- scripts/prebuild.sh
- src/features/ProductPage/transforms.ts
> Fix .productJsonLdProps.reviews serialization error

- next.config.mjs
Opening up the Content Security Policy so users don't have issues with a fairly finnicky system. Everything is still plumbed so this can easily be locked down by somebody who understands it.
> open up csp

- src/features/ProductPage/Product/WithImage/WithImage.tsx
- src/features/ProductPage/Product/WithImageGrid/WithImageGrid.tsx
- src/features/ProductPage/transforms.ts
- src/features/QuickAdd/components/QuickAddItem.tsx
- src/features/QuickAdd/types.ts
- src/utils/hooks/useAddToCart.ts
- src/utils/hooks/useProduct.ts
1. Test product variant selection and add to cart on an ImageGrid product: products/basic-tee-6-pack
1. Test product variant selection and add to cart on an Image product: products/adidas-kids-stan-smith
> New product hooks

- .takeshape/pattern/schema.json
1. Add the schema change to the project, make sure data is created in TS when adding them to Shopify
> Add shopify bootstrap to schema

- .takeshape/pattern/schema.json
1. With a new user go to the subscriptions tab and make sure it loads the correct empty state
> Add defaultValue to Recharge_getMySubscriptions

- README.md
- package-lock.json
- package.json
> Test3 promotion

- README.md
- takeshape-project.graphql
> [Test Branch]

- src/features/AccountSubscriptions/components/ManageSubscription/ManageSubscription.tsx
1. Go to Subscriptions
1. Click on Manage, it should work without err.
> make next charge form conditional

- LICENSE
- README.md
- package.json
1. Confirm that the newly added LICENSE file contains the MIT license
1. Read the new Copyright and License section and check for spelling and grammar errors. Confirm the link to the license file works.
1. Confirm the license property in `package.json` is valid
> Add MIT license to codebase

- src/features/QuickAdd/QuickAdd.tsx
1. Open a quick add
1. Observe close button, click it
> restore close button

- .env
- .env-example
- README.md
- package-lock.json
- package.json
- src/config/dev.ts
- src/config/index.ts
- src/config/site.ts
- src/pages/api/auth/[...nextauth].ts
This URL will only be used in production, so we'll have to verify it post-merge.
Generally, we'll want to check these URLs to ensure the canonical URL is used: `https://penny-ecommerce.vercel.app`
- [sitemap](https://penny-ecommerce.vercel.app/sitemap.xml)
- [openid-config](https://penny-ecommerce.vercel.app/api/auth/all-access/.well-known/openid-configuration)
> use canonical url

- README.md
- package-lock.json
- package.json
- src/config/shopify.ts
- src/features/Cart/utils.ts
1. Checkout on the preview site
1. Ensure you get redirected back to the preview site homepage
> Add configurable checkout URL

- .takeshape/pattern/schema.json
> add ignoreErrors

- src/features/Notification/Notification.tsx
> Fix Timeout types

- README.md
Fix deploy button image
1. 
1. 
1.
> Fix deploy button image

- e2e/constants.ts
- e2e/fake-data-generation.ts
- e2e/tests/contact-form.spec.ts
- e2e/tests/search.spec.ts
- src/features/Navigation/NavigationTop/NavigationTop.tsx
- added new constant and data-testid
- created tests for the search functionality
1. 
1. 
1.
> E2E test for search functionality

- e2e/fake-data-generation.ts
- e2e/page-objects/product-page.ts
- e2e/page-objects/sign-in-page.ts
- e2e/tests/product-page.spec.ts
- playwright.config.ts
- src/features/ProductPage/Reviews/CreateReview.tsx
- src/features/ProductPage/Reviews/Reviews.tsx
- added constants and SignInPage class;
- created a few tests for the review form;
- added new data-testids, and locators for the ProductPage
1. 
1. 
1.
> E2E test for 'Write a review'
